apiVersion: v1
kind: Service
metadata:
  name: application-service-nodeport
spec:
  type: NodePort
  selector:
    app: application-service
  ports:
    - protocol: TCP
      port: 3001     # Service port inside cluster
      targetPort: 3001  # Container port on the pod
      nodePort: 30080   # NodePort (must be in 30000â€“32767)
